### ISSUE TITLE
Memory usage bug

### ISSUE THREAD

**Issue by OmidID** [Wouterdek/NodeNetwork#6]
I have a problem in my project. If you create a tab control and switching between tabs you will see memory increase each time.

![image](https://user-images.githubusercontent.com/956077/40703285-56c4a4be-63ed-11e8-98b3-73928de6bab5.png)

**Comment by Wouterdek** [comment]
Seems you are correct, I am able to reproduce this issue. Probably has something to do with view references getting stuck somewhere.

I will investigate this further, but don't expect a fix in the next month as I currently don't have time to work on this.

**Comment by OmidID** [comment]
@Wouterdek Good news.  I found the bug.

I understand the problem coming from View Location, anytime you open window or do anything it's creating all the views again.

I wrote my own view location resolver and i fixed that some how for my current project.

Refrence: https://reactiveui.net/docs/handbook/views/view-location

```
    public class CacheViewLocator : IViewLocator
    {
        static Dictionary<object, object> cache = new Dictionary<object, object>();
        public static TView CacheView<TKey, TView>(TKey key, Func<TView> ifNotExists)
        {
            object value;
            if (cache.TryGetValue(key, out value))
                if (value is TView) return (TView)value;

            var newValue = ifNotExists();

            if (newValue == null)
                return default(TView);

            cache[key] = newValue;

            return newValue;
        }

        public IViewFor ResolveView<T>(T viewModel, string contract = null) where T : class
        {
            return CacheView(viewModel, () =>
            {
                var type = viewModel.GetType();
                var result = (IViewFor)Splat.Locator.CurrentMutable.GetService(type);
                if (result == null)
                {
                    var ivGenericType = typeof(IViewFor<>);
                    if (!type.IsAssignableFrom(ivGenericType))
                    {
                        result = (IViewFor)Splat.Locator.CurrentMutable.GetService(ivGenericType.MakeGenericType(type));
                    }
                }

                return result;
            });
        }
    }
```

**Comment by Wouterdek** [comment]
I'm glad you found something that works for you.
Note that while this helps reduce memory usage, it doesn't actually resolve the memory leak. When the views stop being used, they should just be released from memory, which currently doesn't seem to be the case.

**Comment by OmidID** [comment]
Exactly. I fixed that temporary for the moment.
Note: Because I have lot of nodes it's take time to show the NetworkView, after i create cache for view i understand it's slow only for first time and after that it's much faster. I mean cache it's not a bad idea to have after you can fix the bug.
Thanks ;)

**Comment by OmidID** [comment]
Looks this is the problem 
https://github.com/reactiveui/ReactiveUI/issues/1314

Do you have any solution for that?

**Comment by Wouterdek** [comment]
In the last few commits, I made changes to the way bindings are created and disposed. 
I have tested the memory usage using dotMemory on a new solution project StressTest, and it seems the memory leak is fixed.

**Comment by OmidID** [comment]
@Wouterdek  The problem still is there, and i don't know why nodes and connection point are default in your last commit!
![image](https://user-images.githubusercontent.com/956077/42363303-bf6676ee-80ff-11e8-8d1d-e6e50e0e0116.png)

**Comment by OmidID** [comment]
Add 500 Nodes randomly and connect them to each other and see how is it working.
At end you will have more than 10k UI element and it's make it really slow.
When you want to move nodes or do anything at line below you have lot of cpu usage.
https://github.com/Wouterdek/NodeNetwork/blob/master/NodeNetwork/Views/PortView.cs#L175

I removed ReactiveUI fully and i modified whole of the project and I made it custom for our self. Almost everything was modified here, and I understand how much ReactiveUI can make it slow. We have to run this app on small control board(custom hardware) with weak CPU, so for us it's important to have really nice performance. I really suggest to do same because it's make it much faster.

Also I had created a custom ItemsControl to avoid creating Canvas for each NodeItem
```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Shapes;

namespace NodeNetwork.Views.Controls
{

    public class ByPassItemControlNewThumbEventArgs : EventArgs
    {
        public Thumb Item { get; set; }
    }

    public class ByPassItemControl : ItemsControl
    {
        private readonly ByPassItemControlNewThumbEventArgs _eventArgs = new ByPassItemControlNewThumbEventArgs();
        public event EventHandler<ByPassItemControlNewThumbEventArgs> NewThumbCreating;

        protected override DependencyObject GetContainerForItemOverride()
        {
            var thumb = new Thumb();
            _eventArgs.Item = thumb;

            NewThumbCreating?.Invoke(this, _eventArgs);

            return _eventArgs.Item;
        }
    }
}
```

```xaml
<controls:ByPassItemControl x:Name="nodesControl" 
                            Width="{Binding ActualWidth, ElementName=contentContainer}" 
                            Height="{Binding ActualHeight, ElementName=contentContainer}"
                            NewThumbCreating="NodesControl_OnNewThumbCreating">
    <controls:ByPassItemControl.ItemContainerStyle>
        <Style TargetType="Thumb">
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="Thumb">
                        <ContentControl Content="{Binding}" HorizontalContentAlignment="Stretch" VerticalContentAlignment="Stretch"/>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
    </controls:ByPassItemControl.ItemContainerStyle>
    <controls:ByPassItemControl.ItemsPanel>
        <ItemsPanelTemplate>
            <Canvas x:Name="localCanvas"></Canvas>
        </ItemsPanelTemplate>
    </controls:ByPassItemControl.ItemsPanel>
</controls:ByPassItemControl>
```

And this is the code in view for the event:
```cs
private void NodesControl_OnNewThumbCreating(object sender, ByPassItemControlNewThumbEventArgs e)
{
    e.Item.DragDelta += OnDragNode;

    BindingOperations.SetBinding(e.Item, Canvas.LeftProperty, new Binding
    {
        Path = new PropertyPath("Position.X"),
        Mode = BindingMode.OneWay,
        UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged
    });
    BindingOperations.SetBinding(e.Item, Canvas.TopProperty, new Binding
    {
        Path = new PropertyPath("Position.Y"),
        Mode = BindingMode.OneWay,
        UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged
    });
}
```

It's make it much faster than before. And also I minified all the themes regarding Microsoft advise
https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/optimizing-performance-layout-and-design

Thank you.

**Comment by Wouterdek** [comment]
Thank you for the suggestions, I will keep them in mind when optimizing performance. I will not be removing ReactiveUI however, since it tightly integrates with an application I am developing. Last week I pushed another commit that updated the binding logic in the example applications and the memory leak is fixed now, so I am closing this issue. If you notice more memory issues, then feel free to comment and I will take a look.
